name: Compile TypeScript

on: [push]

jobs:
  build:
    name: TypeScript Compile

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Node.js dependencies
      run: yarn

    - name: Run build command
      run: yarn build
